// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: `${string}://${string}` | (string & {});
};

/**
 * Body_login_for_access_token_token_post
 */
export type BodyLoginForAccessTokenTokenPost = {
  /**
   * Client Id
   */
  client_id: string | null;
  /**
   * Client Secret
   */
  client_secret: string | null;
  /**
   * Grant Type
   */
  grant_type: string | null;
  /**
   * Password
   */
  password: string;
  /**
   * Scope
   */
  scope: string;
  /**
   * Username
   */
  username: string;
};

/**
 * Body_update_team_logo_tournaments__tournament_id__teams__team_id__logo_post
 */
export type BodyUpdateTeamLogoTournamentsTournamentIdTeamsTeamIdLogoPost = {
  /**
   * File
   */
  file: Blob | File | null;
};

/**
 * Body_upload_logo_tournaments__tournament_id__logo_post
 */
export type BodyUploadLogoTournamentsTournamentIdLogoPost = {
  /**
   * File
   */
  file: Blob | File | null;
};

/**
 * BracketPosition
 */
export type BracketPosition = 'WINNERS' | 'LOSERS' | 'GRAND_FINALS' | 'NONE';

/**
 * Club
 */
export type Club = {
  /**
   * Created
   */
  created: string;
  /**
   * Id
   */
  id: number;
  /**
   * Name
   */
  name: string;
};

/**
 * ClubCreateBody
 */
export type ClubCreateBody = {
  /**
   * Name
   */
  name: string;
};

/**
 * ClubResponse
 */
export type ClubResponse = {
  data: Club | null;
};

/**
 * ClubUpdateBody
 */
export type ClubUpdateBody = {
  /**
   * Name
   */
  name: string;
};

/**
 * ClubsResponse
 */
export type ClubsResponse = {
  /**
   * Data
   */
  data: Array<Club>;
};

/**
 * Court
 */
export type Court = {
  /**
   * Created
   */
  created: string;
  /**
   * Id
   */
  id: number;
  /**
   * Name
   */
  name: string;
  /**
   * Tournament Id
   */
  tournament_id: number;
};

/**
 * CourtBody
 */
export type CourtBody = {
  /**
   * Name
   */
  name: string;
};

/**
 * CourtsResponse
 */
export type CourtsResponse = {
  /**
   * Data
   */
  data: Array<Court>;
};

/**
 * DemoUserToRegister
 */
export type DemoUserToRegister = {
  /**
   * Captcha Token
   */
  captcha_token: string;
};

/**
 * FullTeamWithPlayers
 */
export type FullTeamWithPlayers = {
  /**
   * Active
   */
  active: boolean;
  /**
   * Created
   */
  created: string;
  /**
   * Draws
   */
  draws: number;
  /**
   * Elo Score
   */
  elo_score: string;
  /**
   * Id
   */
  id: number;
  /**
   * Logo Path
   */
  logo_path: string | null;
  /**
   * Losses
   */
  losses: number;
  /**
   * Name
   */
  name: string;
  /**
   * Players
   */
  players: Array<Player>;
  /**
   * Swiss Score
   */
  swiss_score: string;
  /**
   * Tournament Id
   */
  tournament_id: number;
  /**
   * Wins
   */
  wins: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * Match
 */
export type Match = {
  /**
   * Court Id
   */
  court_id: number | null;
  /**
   * Created
   */
  created: string;
  /**
   * Custom Duration Minutes
   */
  custom_duration_minutes: number | null;
  /**
   * Custom Margin Minutes
   */
  custom_margin_minutes: number | null;
  /**
   * Duration Minutes
   */
  duration_minutes: number;
  /**
   * Id
   */
  id: number;
  /**
   * Margin Minutes
   */
  margin_minutes: number;
  /**
   * Official Id
   */
  official_id: number | null;
  /**
   * Pending Score1
   */
  pending_score1: number | null;
  /**
   * Pending Score2
   */
  pending_score2: number | null;
  /**
   * Position In Schedule
   */
  position_in_schedule: number | null;
  /**
   * Round Id
   */
  round_id: number;
  /**
   * Stage Item Input1
   */
  stage_item_input1: StageItemInputTentative | StageItemInputFinal | StageItemInputEmpty | null;
  /**
   * Stage Item Input1 Conflict
   */
  stage_item_input1_conflict: boolean;
  /**
   * Stage Item Input1 Id
   */
  stage_item_input1_id: number | null;
  /**
   * Stage Item Input1 Loser From Match Id
   */
  stage_item_input1_loser_from_match_id: number | null;
  /**
   * Stage Item Input1 Score
   */
  stage_item_input1_score: number;
  /**
   * Stage Item Input1 Winner From Match Id
   */
  stage_item_input1_winner_from_match_id: number | null;
  /**
   * Stage Item Input2
   */
  stage_item_input2: StageItemInputTentative | StageItemInputFinal | StageItemInputEmpty | null;
  /**
   * Stage Item Input2 Conflict
   */
  stage_item_input2_conflict: boolean;
  /**
   * Stage Item Input2 Id
   */
  stage_item_input2_id: number | null;
  /**
   * Stage Item Input2 Loser From Match Id
   */
  stage_item_input2_loser_from_match_id: number | null;
  /**
   * Stage Item Input2 Score
   */
  stage_item_input2_score: number;
  /**
   * Stage Item Input2 Winner From Match Id
   */
  stage_item_input2_winner_from_match_id: number | null;
  /**
   * Start Time
   */
  start_time: string | null;
};

/**
 * MatchBody
 */
export type MatchBody = {
  /**
   * Court Id
   */
  court_id: number | null;
  /**
   * Custom Duration Minutes
   */
  custom_duration_minutes: number | null;
  /**
   * Custom Margin Minutes
   */
  custom_margin_minutes: number | null;
  /**
   * Official Id
   */
  official_id: number | null;
  /**
   * Round Id
   */
  round_id: number;
  /**
   * Stage Item Input1 Score
   */
  stage_item_input1_score: number;
  /**
   * Stage Item Input2 Score
   */
  stage_item_input2_score: number;
  /**
   * Start Time
   */
  start_time: string | null;
};

/**
 * MatchCreateBodyFrontend
 */
export type MatchCreateBodyFrontend = {
  /**
   * Court Id
   */
  court_id: number | null;
  /**
   * Round Id
   */
  round_id: number;
  /**
   * Stage Item Input1 Id
   */
  stage_item_input1_id: number | null;
  /**
   * Stage Item Input1 Loser From Match Id
   */
  stage_item_input1_loser_from_match_id: number | null;
  /**
   * Stage Item Input1 Winner From Match Id
   */
  stage_item_input1_winner_from_match_id: number | null;
  /**
   * Stage Item Input2 Id
   */
  stage_item_input2_id: number | null;
  /**
   * Stage Item Input2 Loser From Match Id
   */
  stage_item_input2_loser_from_match_id: number | null;
  /**
   * Stage Item Input2 Winner From Match Id
   */
  stage_item_input2_winner_from_match_id: number | null;
};

/**
 * MatchRescheduleBody
 */
export type MatchRescheduleBody = {
  /**
   * New Court Id
   */
  new_court_id: number;
  /**
   * New Position
   */
  new_position: number;
  /**
   * Old Court Id
   */
  old_court_id: number;
  /**
   * Old Position
   */
  old_position: number;
};

/**
 * MatchWithDetails
 *
 * MatchWithDetails has zero or one defined stage item inputs, but not both.
 */
export type MatchWithDetails = {
  court: Court | null;
  /**
   * Court Id
   */
  court_id: number | null;
  /**
   * Created
   */
  created: string;
  /**
   * Custom Duration Minutes
   */
  custom_duration_minutes: number | null;
  /**
   * Custom Margin Minutes
   */
  custom_margin_minutes: number | null;
  /**
   * Duration Minutes
   */
  duration_minutes: number;
  /**
   * Id
   */
  id: number;
  /**
   * Margin Minutes
   */
  margin_minutes: number;
  official: Official | null;
  /**
   * Official Id
   */
  official_id: number | null;
  /**
   * Pending Score1
   */
  pending_score1: number | null;
  /**
   * Pending Score2
   */
  pending_score2: number | null;
  /**
   * Position In Schedule
   */
  position_in_schedule: number | null;
  /**
   * Round Id
   */
  round_id: number;
  /**
   * Stage Item Input1
   */
  stage_item_input1: StageItemInputTentative | StageItemInputFinal | StageItemInputEmpty | null;
  /**
   * Stage Item Input1 Conflict
   */
  stage_item_input1_conflict: boolean;
  /**
   * Stage Item Input1 Id
   */
  stage_item_input1_id: number | null;
  /**
   * Stage Item Input1 Loser From Match Id
   */
  stage_item_input1_loser_from_match_id: number | null;
  /**
   * Stage Item Input1 Score
   */
  stage_item_input1_score: number;
  /**
   * Stage Item Input1 Winner From Match Id
   */
  stage_item_input1_winner_from_match_id: number | null;
  /**
   * Stage Item Input2
   */
  stage_item_input2: StageItemInputTentative | StageItemInputFinal | StageItemInputEmpty | null;
  /**
   * Stage Item Input2 Conflict
   */
  stage_item_input2_conflict: boolean;
  /**
   * Stage Item Input2 Id
   */
  stage_item_input2_id: number | null;
  /**
   * Stage Item Input2 Loser From Match Id
   */
  stage_item_input2_loser_from_match_id: number | null;
  /**
   * Stage Item Input2 Score
   */
  stage_item_input2_score: number;
  /**
   * Stage Item Input2 Winner From Match Id
   */
  stage_item_input2_winner_from_match_id: number | null;
  /**
   * Start Time
   */
  start_time: string | null;
};

/**
 * MatchWithDetailsDefinitive
 */
export type MatchWithDetailsDefinitive = {
  court: Court | null;
  /**
   * Court Id
   */
  court_id: number | null;
  /**
   * Created
   */
  created: string;
  /**
   * Custom Duration Minutes
   */
  custom_duration_minutes: number | null;
  /**
   * Custom Margin Minutes
   */
  custom_margin_minutes: number | null;
  /**
   * Duration Minutes
   */
  duration_minutes: number;
  /**
   * Id
   */
  id: number;
  /**
   * Margin Minutes
   */
  margin_minutes: number;
  official: Official | null;
  /**
   * Official Id
   */
  official_id: number | null;
  /**
   * Pending Score1
   */
  pending_score1: number | null;
  /**
   * Pending Score2
   */
  pending_score2: number | null;
  /**
   * Position In Schedule
   */
  position_in_schedule: number | null;
  /**
   * Round Id
   */
  round_id: number;
  /**
   * Stage Item Input1
   */
  stage_item_input1: StageItemInputTentative | StageItemInputFinal | StageItemInputEmpty;
  /**
   * Stage Item Input1 Conflict
   */
  stage_item_input1_conflict: boolean;
  /**
   * Stage Item Input1 Id
   */
  stage_item_input1_id: number | null;
  /**
   * Stage Item Input1 Loser From Match Id
   */
  stage_item_input1_loser_from_match_id: number | null;
  /**
   * Stage Item Input1 Score
   */
  stage_item_input1_score: number;
  /**
   * Stage Item Input1 Winner From Match Id
   */
  stage_item_input1_winner_from_match_id: number | null;
  /**
   * Stage Item Input2
   */
  stage_item_input2: StageItemInputTentative | StageItemInputFinal | StageItemInputEmpty;
  /**
   * Stage Item Input2 Conflict
   */
  stage_item_input2_conflict: boolean;
  /**
   * Stage Item Input2 Id
   */
  stage_item_input2_id: number | null;
  /**
   * Stage Item Input2 Loser From Match Id
   */
  stage_item_input2_loser_from_match_id: number | null;
  /**
   * Stage Item Input2 Score
   */
  stage_item_input2_score: number;
  /**
   * Stage Item Input2 Winner From Match Id
   */
  stage_item_input2_winner_from_match_id: number | null;
  /**
   * Start Time
   */
  start_time: string | null;
};

/**
 * Official
 */
export type Official = {
  /**
   * Access Code
   */
  access_code: string;
  /**
   * Created
   */
  created: string;
  /**
   * Id
   */
  id: number;
  /**
   * Name
   */
  name: string;
  /**
   * Tournament Id
   */
  tournament_id: number;
};

/**
 * OfficialBody
 */
export type OfficialBody = {
  /**
   * Name
   */
  name: string;
};

/**
 * OfficialsResponse
 */
export type OfficialsResponse = {
  /**
   * Data
   */
  data: Array<Official>;
};

/**
 * PaginatedPlayers
 */
export type PaginatedPlayers = {
  /**
   * Count
   */
  count: number;
  /**
   * Players
   */
  players: Array<Player>;
};

/**
 * PaginatedTeams
 */
export type PaginatedTeams = {
  /**
   * Count
   */
  count: number;
  /**
   * Teams
   */
  teams: Array<FullTeamWithPlayers>;
};

/**
 * Player
 */
export type Player = {
  /**
   * Active
   */
  active: boolean;
  /**
   * Created
   */
  created: string;
  /**
   * Draws
   */
  draws: number;
  /**
   * Elo Score
   */
  elo_score: string;
  /**
   * Id
   */
  id: number;
  /**
   * Losses
   */
  losses: number;
  /**
   * Name
   */
  name: string;
  /**
   * Swiss Score
   */
  swiss_score: string;
  /**
   * Tournament Id
   */
  tournament_id: number;
  /**
   * Wins
   */
  wins: number;
};

/**
 * PlayerBody
 */
export type PlayerBody = {
  /**
   * Active
   */
  active: boolean;
  /**
   * Name
   */
  name: string;
};

/**
 * PlayerMultiBody
 */
export type PlayerMultiBody = {
  /**
   * Active
   */
  active: boolean;
  /**
   * Names
   */
  names: string;
};

/**
 * PlayersResponse
 */
export type PlayersResponse = {
  data: PaginatedPlayers;
};

/**
 * PortalLoginBody
 */
export type PortalLoginBody = {
  /**
   * Access Code
   */
  access_code: string;
};

/**
 * PortalLoginResponse
 */
export type PortalLoginResponse = {
  official: Official;
  /**
   * Tournament Id
   */
  tournament_id: number;
};

/**
 * PortalMatch
 */
export type PortalMatch = {
  /**
   * Court Name
   */
  court_name: string | null;
  /**
   * Id
   */
  id: number;
  /**
   * Position In Schedule
   */
  position_in_schedule: number | null;
  /**
   * Stage Item Input1 Score
   */
  stage_item_input1_score: number;
  /**
   * Stage Item Input2 Score
   */
  stage_item_input2_score: number;
  /**
   * Start Time
   */
  start_time: string | null;
  /**
   * Team1 Name
   */
  team1_name: string | null;
  /**
   * Team2 Name
   */
  team2_name: string | null;
};

/**
 * PortalMatchesResponse
 */
export type PortalMatchesResponse = {
  /**
   * Data
   */
  data: Array<PortalMatch>;
};

/**
 * PortalPendingScoreBody
 */
export type PortalPendingScoreBody = {
  /**
   * Pending Score1
   */
  pending_score1: number;
  /**
   * Pending Score2
   */
  pending_score2: number;
};

/**
 * PortalScoreBody
 */
export type PortalScoreBody = {
  /**
   * Stage Item Input1 Score
   */
  stage_item_input1_score: number;
  /**
   * Stage Item Input2 Score
   */
  stage_item_input2_score: number;
};

/**
 * Ranking
 */
export type Ranking = {
  /**
   * Add Score Points
   */
  add_score_points: boolean;
  /**
   * Created
   */
  created: string;
  /**
   * Draw Points
   */
  draw_points: string;
  /**
   * Id
   */
  id: number;
  /**
   * Loss Points
   */
  loss_points: string;
  /**
   * Position
   */
  position: number;
  /**
   * Tournament Id
   */
  tournament_id: number;
  /**
   * Win Points
   */
  win_points: string;
};

/**
 * RankingBody
 */
export type RankingBody = {
  /**
   * Add Score Points
   */
  add_score_points: boolean;
  /**
   * Draw Points
   */
  draw_points: number | string;
  /**
   * Loss Points
   */
  loss_points: number | string;
  /**
   * Position
   */
  position: number;
  /**
   * Win Points
   */
  win_points: number | string;
};

/**
 * RankingCreateBody
 */
export type RankingCreateBody = {
  /**
   * Add Score Points
   */
  add_score_points: boolean;
  /**
   * Draw Points
   */
  draw_points: number | string;
  /**
   * Loss Points
   */
  loss_points: number | string;
  /**
   * Win Points
   */
  win_points: number | string;
};

/**
 * RankingsResponse
 */
export type RankingsResponse = {
  /**
   * Data
   */
  data: Array<Ranking>;
};

/**
 * RoundCreateBody
 */
export type RoundCreateBody = {
  /**
   * Name
   */
  name: string | null;
  /**
   * Stage Item Id
   */
  stage_item_id: number;
};

/**
 * RoundUpdateBody
 */
export type RoundUpdateBody = {
  /**
   * Is Draft
   */
  is_draft: boolean;
  /**
   * Name
   */
  name: string;
};

/**
 * RoundWithMatches
 */
export type RoundWithMatches = {
  bracket_position: BracketPosition;
  /**
   * Created
   */
  created: string;
  /**
   * Id
   */
  id: number;
  /**
   * Is Draft
   */
  is_draft: boolean;
  /**
   * Matches
   */
  matches: Array<MatchWithDetailsDefinitive | MatchWithDetails>;
  /**
   * Name
   */
  name: string;
  /**
   * Stage Item Id
   */
  stage_item_id: number;
};

/**
 * SingleCourtResponse
 */
export type SingleCourtResponse = {
  data: Court;
};

/**
 * SingleMatchResponse
 */
export type SingleMatchResponse = {
  data: Match;
};

/**
 * SingleOfficialResponse
 */
export type SingleOfficialResponse = {
  data: Official;
};

/**
 * SinglePlayerResponse
 */
export type SinglePlayerResponse = {
  data: Player;
};

/**
 * SingleTeamResponse
 */
export type SingleTeamResponse = {
  data: Team;
};

/**
 * SingleTournamentBreakResponse
 */
export type SingleTournamentBreakResponse = {
  data: TournamentBreak;
};

/**
 * StageActivateBody
 */
export type StageActivateBody = {
  /**
   * Direction
   */
  direction: 'next' | 'previous';
};

/**
 * StageItemActivateNextBody
 */
export type StageItemActivateNextBody = {
  /**
   * Adjust To Time
   */
  adjust_to_time: string | null;
};

/**
 * StageItemCreateBody
 */
export type StageItemCreateBody = {
  /**
   * Name
   */
  name: string | null;
  /**
   * Ranking Id
   */
  ranking_id: number | null;
  /**
   * Stage Id
   */
  stage_id: number;
  /**
   * Team Count
   */
  team_count: number;
  type: StageType;
};

/**
 * StageItemInputEmpty
 */
export type StageItemInputEmpty = {
  /**
   * Draws
   */
  draws: number;
  /**
   * Id
   */
  id: number;
  /**
   * Losses
   */
  losses: number;
  /**
   * Points
   */
  points: string;
  /**
   * Slot
   */
  slot: number;
  /**
   * Stage Item Id
   */
  stage_item_id: number | null;
  /**
   * Team Id
   */
  team_id: null;
  /**
   * Tournament Id
   */
  tournament_id: number;
  /**
   * Winner From Stage Item Id
   */
  winner_from_stage_item_id: null;
  /**
   * Winner Position
   */
  winner_position: null;
  /**
   * Wins
   */
  wins: number;
};

/**
 * StageItemInputFinal
 */
export type StageItemInputFinal = {
  /**
   * Draws
   */
  draws: number;
  /**
   * Id
   */
  id: number;
  /**
   * Losses
   */
  losses: number;
  /**
   * Points
   */
  points: string;
  /**
   * Slot
   */
  slot: number;
  /**
   * Stage Item Id
   */
  stage_item_id: number | null;
  team: Team;
  /**
   * Team Id
   */
  team_id: number;
  /**
   * Tournament Id
   */
  tournament_id: number;
  /**
   * Winner From Stage Item Id
   */
  winner_from_stage_item_id: number | null;
  /**
   * Winner Position
   */
  winner_position: number | null;
  /**
   * Wins
   */
  wins: number;
};

/**
 * StageItemInputOptionFinal
 */
export type StageItemInputOptionFinal = {
  /**
   * Already Taken
   */
  already_taken: boolean;
  /**
   * Team Id
   */
  team_id: number;
};

/**
 * StageItemInputOptionTentative
 */
export type StageItemInputOptionTentative = {
  /**
   * Already Taken
   */
  already_taken: boolean;
  /**
   * Winner From Stage Item Id
   */
  winner_from_stage_item_id: number;
  /**
   * Winner Position
   */
  winner_position: number;
};

/**
 * StageItemInputOptionsResponse
 */
export type StageItemInputOptionsResponse = {
  /**
   * Data
   */
  data: {
    [key: string]: Array<StageItemInputOptionTentative | StageItemInputOptionFinal>;
  };
};

/**
 * StageItemInputTentative
 */
export type StageItemInputTentative = {
  /**
   * Draws
   */
  draws: number;
  /**
   * Id
   */
  id: number;
  /**
   * Losses
   */
  losses: number;
  /**
   * Points
   */
  points: string;
  /**
   * Slot
   */
  slot: number;
  /**
   * Stage Item Id
   */
  stage_item_id: number | null;
  /**
   * Team Id
   */
  team_id: null;
  /**
   * Tournament Id
   */
  tournament_id: number;
  /**
   * Winner From Stage Item Id
   */
  winner_from_stage_item_id: number;
  /**
   * Winner Position
   */
  winner_position: number;
  /**
   * Wins
   */
  wins: number;
};

/**
 * StageItemInputUpdate
 */
export type StageItemInputUpdate = {
  stage_item_input: StageItemInputTentative;
  team: Team;
};

/**
 * StageItemInputUpdateBodyEmpty
 */
export type StageItemInputUpdateBodyEmpty = {
  /**
   * Team Id
   */
  team_id: null;
  /**
   * Winner From Stage Item Id
   */
  winner_from_stage_item_id: null;
  /**
   * Winner Position
   */
  winner_position: null;
};

/**
 * StageItemInputUpdateBodyFinal
 */
export type StageItemInputUpdateBodyFinal = {
  /**
   * Team Id
   */
  team_id: number;
};

/**
 * StageItemInputUpdateBodyTentative
 */
export type StageItemInputUpdateBodyTentative = {
  /**
   * Winner From Stage Item Id
   */
  winner_from_stage_item_id: number;
  /**
   * Winner Position
   */
  winner_position: number;
};

/**
 * StageItemUpdateBody
 */
export type StageItemUpdateBody = {
  /**
   * Name
   */
  name: string;
  /**
   * Ranking Id
   */
  ranking_id: number;
};

/**
 * StageItemWithRounds
 */
export type StageItemWithRounds = {
  /**
   * Created
   */
  created: string;
  /**
   * Id
   */
  id: number;
  /**
   * Inputs
   */
  inputs: Array<StageItemInputTentative | StageItemInputFinal | StageItemInputEmpty>;
  /**
   * Name
   */
  name: string;
  /**
   * Ranking Id
   */
  ranking_id: number | null;
  /**
   * Rounds
   */
  rounds: Array<RoundWithMatches>;
  /**
   * Stage Id
   */
  stage_id: number;
  /**
   * Team Count
   */
  team_count: number;
  type: StageType;
  /**
   * Type Name
   */
  type_name: string;
};

/**
 * StageRankingResponse
 */
export type StageRankingResponse = {
  /**
   * Data
   */
  data: {
    [key: string]: Array<StageItemInputUpdate>;
  };
};

/**
 * StageType
 */
export type StageType = 'ROUND_ROBIN' | 'SINGLE_ELIMINATION' | 'DOUBLE_ELIMINATION' | 'SWISS';

/**
 * StageUpdateBody
 */
export type StageUpdateBody = {
  /**
   * Name
   */
  name: string;
};

/**
 * StageWithStageItems
 */
export type StageWithStageItems = {
  /**
   * Created
   */
  created: string;
  /**
   * Id
   */
  id: number;
  /**
   * Is Active
   */
  is_active: boolean;
  /**
   * Name
   */
  name: string;
  /**
   * Stage Items
   */
  stage_items: Array<StageItemWithRounds>;
  /**
   * Tournament Id
   */
  tournament_id: number;
};

/**
 * StagesWithStageItemsResponse
 */
export type StagesWithStageItemsResponse = {
  /**
   * Data
   */
  data: Array<StageWithStageItems>;
};

/**
 * SuccessResponse
 */
export type SuccessResponse = {
  /**
   * Success
   */
  success: boolean;
};

/**
 * SuggestedMatch
 */
export type SuggestedMatch = {
  /**
   * Elo Diff
   */
  elo_diff: string;
  /**
   * Is Recommended
   */
  is_recommended: boolean;
  /**
   * Player Behind Schedule Count
   */
  player_behind_schedule_count: number;
  /**
   * Stage Item Input1
   */
  stage_item_input1: StageItemInputTentative | StageItemInputFinal | StageItemInputEmpty;
  /**
   * Stage Item Input2
   */
  stage_item_input2: StageItemInputTentative | StageItemInputFinal | StageItemInputEmpty;
  /**
   * Swiss Diff
   */
  swiss_diff: string;
  /**
   * Times Played Sum
   */
  times_played_sum: number;
};

/**
 * Team
 */
export type Team = {
  /**
   * Active
   */
  active: boolean;
  /**
   * Created
   */
  created: string;
  /**
   * Draws
   */
  draws: number;
  /**
   * Elo Score
   */
  elo_score: string;
  /**
   * Id
   */
  id: number;
  /**
   * Logo Path
   */
  logo_path: string | null;
  /**
   * Losses
   */
  losses: number;
  /**
   * Name
   */
  name: string;
  /**
   * Swiss Score
   */
  swiss_score: string;
  /**
   * Tournament Id
   */
  tournament_id: number;
  /**
   * Wins
   */
  wins: number;
};

/**
 * TeamBody
 */
export type TeamBody = {
  /**
   * Active
   */
  active: boolean;
  /**
   * Name
   */
  name: string;
  /**
   * Player Ids
   */
  player_ids: Array<number>;
};

/**
 * TeamMultiBody
 */
export type TeamMultiBody = {
  /**
   * Active
   */
  active: boolean;
  /**
   * Names
   */
  names: string;
};

/**
 * TeamsWithPlayersResponse
 */
export type TeamsWithPlayersResponse = {
  data: PaginatedTeams;
};

/**
 * Token
 */
export type Token = {
  /**
   * Access Token
   */
  access_token: string;
  /**
   * Token Type
   */
  token_type: string;
  /**
   * User Id
   */
  user_id: number;
};

/**
 * TokenResponse
 */
export type TokenResponse = {
  data: Token;
};

/**
 * Tournament
 */
export type Tournament = {
  /**
   * Auto Assign Courts
   */
  auto_assign_courts: boolean;
  /**
   * Club Id
   */
  club_id: number;
  /**
   * Created
   */
  created: string;
  /**
   * Dashboard Endpoint
   */
  dashboard_endpoint: string | null;
  /**
   * Dashboard Public
   */
  dashboard_public: boolean;
  /**
   * Dashboard Show Standings
   */
  dashboard_show_standings: boolean;
  /**
   * Duration Minutes
   */
  duration_minutes: number;
  /**
   * Id
   */
  id: number;
  /**
   * Logo Path
   */
  logo_path: string | null;
  /**
   * Margin Minutes
   */
  margin_minutes: number;
  /**
   * Name
   */
  name: string;
  /**
   * Players Can Be In Multiple Teams
   */
  players_can_be_in_multiple_teams: boolean;
  /**
   * Start Time
   */
  start_time: string;
  status: TournamentStatus;
};

/**
 * TournamentBody
 */
export type TournamentBody = {
  /**
   * Auto Assign Courts
   */
  auto_assign_courts: boolean;
  /**
   * Club Id
   */
  club_id: number;
  /**
   * Dashboard Endpoint
   */
  dashboard_endpoint: unknown | string;
  /**
   * Dashboard Public
   */
  dashboard_public: boolean;
  /**
   * Dashboard Show Standings
   */
  dashboard_show_standings: boolean;
  /**
   * Duration Minutes
   */
  duration_minutes: number;
  /**
   * Margin Minutes
   */
  margin_minutes: number;
  /**
   * Name
   */
  name: string;
  /**
   * Players Can Be In Multiple Teams
   */
  players_can_be_in_multiple_teams: boolean;
  /**
   * Start Time
   */
  start_time: string;
};

/**
 * TournamentBreak
 */
export type TournamentBreak = {
  /**
   * Created
   */
  created: string;
  /**
   * End Time
   */
  end_time: string;
  /**
   * Id
   */
  id: number;
  /**
   * Start Time
   */
  start_time: string;
  /**
   * Title
   */
  title: string;
  /**
   * Tournament Id
   */
  tournament_id: number;
};

/**
 * TournamentBreakBody
 */
export type TournamentBreakBody = {
  /**
   * End Time
   */
  end_time: string;
  /**
   * Start Time
   */
  start_time: string;
  /**
   * Title
   */
  title: string;
};

/**
 * TournamentBreaksResponse
 */
export type TournamentBreaksResponse = {
  /**
   * Data
   */
  data: Array<TournamentBreak>;
};

/**
 * TournamentChangeStatusBody
 */
export type TournamentChangeStatusBody = {
  status: TournamentStatus;
};

/**
 * TournamentResponse
 */
export type TournamentResponse = {
  data: Tournament;
};

/**
 * TournamentStatus
 */
export type TournamentStatus = 'OPEN' | 'ARCHIVED';

/**
 * TournamentUpdateBody
 */
export type TournamentUpdateBody = {
  /**
   * Auto Assign Courts
   */
  auto_assign_courts: boolean;
  /**
   * Dashboard Endpoint
   */
  dashboard_endpoint: unknown | string;
  /**
   * Dashboard Public
   */
  dashboard_public: boolean;
  /**
   * Dashboard Show Standings
   */
  dashboard_show_standings: boolean;
  /**
   * Duration Minutes
   */
  duration_minutes: number;
  /**
   * Margin Minutes
   */
  margin_minutes: number;
  /**
   * Name
   */
  name: string;
  /**
   * Players Can Be In Multiple Teams
   */
  players_can_be_in_multiple_teams: boolean;
  /**
   * Start Time
   */
  start_time: string;
};

/**
 * TournamentsResponse
 */
export type TournamentsResponse = {
  /**
   * Data
   */
  data: Array<Tournament>;
};

/**
 * UpcomingMatchesResponse
 */
export type UpcomingMatchesResponse = {
  /**
   * Data
   */
  data: Array<SuggestedMatch>;
};

/**
 * UserAccountType
 */
export type UserAccountType = 'REGULAR' | 'DEMO';

/**
 * UserPasswordToUpdate
 */
export type UserPasswordToUpdate = {
  /**
   * Password
   */
  password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
  account_type: UserAccountType;
  /**
   * Created
   */
  created: string;
  /**
   * Email
   */
  email: string;
  /**
   * Id
   */
  id: number;
  /**
   * Name
   */
  name: string;
};

/**
 * UserPublicResponse
 */
export type UserPublicResponse = {
  data: UserPublic;
};

/**
 * UserToRegister
 */
export type UserToRegister = {
  /**
   * Captcha Token
   */
  captcha_token: string;
  /**
   * Email
   */
  email: string;
  /**
   * Name
   */
  name: string;
  /**
   * Password
   */
  password: string;
};

/**
 * UserToUpdate
 */
export type UserToUpdate = {
  /**
   * Email
   */
  email: string;
  /**
   * Name
   */
  name: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

export type GetClubsClubsGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/clubs';
};

export type GetClubsClubsGetResponses = {
  /**
   * Successful Response
   */
  200: ClubsResponse;
};

export type GetClubsClubsGetResponse = GetClubsClubsGetResponses[keyof GetClubsClubsGetResponses];

export type CreateNewClubClubsPostData = {
  body: ClubCreateBody;
  path?: never;
  query?: never;
  url: '/clubs';
};

export type CreateNewClubClubsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateNewClubClubsPostError =
  CreateNewClubClubsPostErrors[keyof CreateNewClubClubsPostErrors];

export type CreateNewClubClubsPostResponses = {
  /**
   * Successful Response
   */
  200: ClubResponse;
};

export type CreateNewClubClubsPostResponse =
  CreateNewClubClubsPostResponses[keyof CreateNewClubClubsPostResponses];

export type DeleteClubClubsClubIdDeleteData = {
  body?: never;
  path: {
    /**
     * Club Id
     */
    club_id: number;
  };
  query?: never;
  url: '/clubs/{club_id}';
};

export type DeleteClubClubsClubIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteClubClubsClubIdDeleteError =
  DeleteClubClubsClubIdDeleteErrors[keyof DeleteClubClubsClubIdDeleteErrors];

export type DeleteClubClubsClubIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type DeleteClubClubsClubIdDeleteResponse =
  DeleteClubClubsClubIdDeleteResponses[keyof DeleteClubClubsClubIdDeleteResponses];

export type UpdateClubClubsClubIdPutData = {
  body: ClubUpdateBody;
  path: {
    /**
     * Club Id
     */
    club_id: number;
  };
  query?: never;
  url: '/clubs/{club_id}';
};

export type UpdateClubClubsClubIdPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateClubClubsClubIdPutError =
  UpdateClubClubsClubIdPutErrors[keyof UpdateClubClubsClubIdPutErrors];

export type UpdateClubClubsClubIdPutResponses = {
  /**
   * Successful Response
   */
  200: ClubResponse;
};

export type UpdateClubClubsClubIdPutResponse =
  UpdateClubClubsClubIdPutResponses[keyof UpdateClubClubsClubIdPutResponses];

export type GetMetricsMetricsGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/metrics';
};

export type GetMetricsMetricsGetResponses = {
  /**
   * Successful Response
   */
  200: string;
};

export type GetMetricsMetricsGetResponse =
  GetMetricsMetricsGetResponses[keyof GetMetricsMetricsGetResponses];

export type PortalLoginOfficialPortalLoginPostData = {
  body: PortalLoginBody;
  path?: never;
  query?: never;
  url: '/official_portal/login';
};

export type PortalLoginOfficialPortalLoginPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type PortalLoginOfficialPortalLoginPostError =
  PortalLoginOfficialPortalLoginPostErrors[keyof PortalLoginOfficialPortalLoginPostErrors];

export type PortalLoginOfficialPortalLoginPostResponses = {
  /**
   * Successful Response
   */
  200: PortalLoginResponse;
};

export type PortalLoginOfficialPortalLoginPostResponse =
  PortalLoginOfficialPortalLoginPostResponses[keyof PortalLoginOfficialPortalLoginPostResponses];

export type PortalGetMatchesOfficialPortalMatchesGetData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Access Code
     */
    access_code: string;
  };
  url: '/official_portal/matches';
};

export type PortalGetMatchesOfficialPortalMatchesGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type PortalGetMatchesOfficialPortalMatchesGetError =
  PortalGetMatchesOfficialPortalMatchesGetErrors[keyof PortalGetMatchesOfficialPortalMatchesGetErrors];

export type PortalGetMatchesOfficialPortalMatchesGetResponses = {
  /**
   * Successful Response
   */
  200: PortalMatchesResponse;
};

export type PortalGetMatchesOfficialPortalMatchesGetResponse =
  PortalGetMatchesOfficialPortalMatchesGetResponses[keyof PortalGetMatchesOfficialPortalMatchesGetResponses];

export type PortalUpdatePendingScoreOfficialPortalMatchesMatchIdPendingScorePutData = {
  body: PortalPendingScoreBody;
  path: {
    /**
     * Match Id
     */
    match_id: number;
  };
  query: {
    /**
     * Access Code
     */
    access_code: string;
  };
  url: '/official_portal/matches/{match_id}/pending_score';
};

export type PortalUpdatePendingScoreOfficialPortalMatchesMatchIdPendingScorePutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type PortalUpdatePendingScoreOfficialPortalMatchesMatchIdPendingScorePutError =
  PortalUpdatePendingScoreOfficialPortalMatchesMatchIdPendingScorePutErrors[keyof PortalUpdatePendingScoreOfficialPortalMatchesMatchIdPendingScorePutErrors];

export type PortalUpdatePendingScoreOfficialPortalMatchesMatchIdPendingScorePutResponses = {
  /**
   * Response Portal Update Pending Score Official Portal Matches  Match Id  Pending Score Put
   *
   * Successful Response
   */
  200: {
    [key: string]: boolean;
  };
};

export type PortalUpdatePendingScoreOfficialPortalMatchesMatchIdPendingScorePutResponse =
  PortalUpdatePendingScoreOfficialPortalMatchesMatchIdPendingScorePutResponses[keyof PortalUpdatePendingScoreOfficialPortalMatchesMatchIdPendingScorePutResponses];

export type PortalSubmitScoreOfficialPortalMatchesMatchIdScorePutData = {
  body: PortalScoreBody;
  path: {
    /**
     * Match Id
     */
    match_id: number;
  };
  query: {
    /**
     * Access Code
     */
    access_code: string;
  };
  url: '/official_portal/matches/{match_id}/score';
};

export type PortalSubmitScoreOfficialPortalMatchesMatchIdScorePutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type PortalSubmitScoreOfficialPortalMatchesMatchIdScorePutError =
  PortalSubmitScoreOfficialPortalMatchesMatchIdScorePutErrors[keyof PortalSubmitScoreOfficialPortalMatchesMatchIdScorePutErrors];

export type PortalSubmitScoreOfficialPortalMatchesMatchIdScorePutResponses = {
  /**
   * Response Portal Submit Score Official Portal Matches  Match Id  Score Put
   *
   * Successful Response
   */
  200: {
    [key: string]: boolean;
  };
};

export type PortalSubmitScoreOfficialPortalMatchesMatchIdScorePutResponse =
  PortalSubmitScoreOfficialPortalMatchesMatchIdScorePutResponses[keyof PortalSubmitScoreOfficialPortalMatchesMatchIdScorePutResponses];

export type PingPingGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/ping';
};

export type PingPingGetResponses = {
  /**
   * Response Ping Ping Get
   *
   * Successful Response
   */
  200: string;
};

export type PingPingGetResponse = PingPingGetResponses[keyof PingPingGetResponses];

export type LoginForAccessTokenTokenPostData = {
  body: BodyLoginForAccessTokenTokenPost;
  path?: never;
  query?: never;
  url: '/token';
};

export type LoginForAccessTokenTokenPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type LoginForAccessTokenTokenPostError =
  LoginForAccessTokenTokenPostErrors[keyof LoginForAccessTokenTokenPostErrors];

export type LoginForAccessTokenTokenPostResponses = {
  /**
   * Successful Response
   */
  200: Token;
};

export type LoginForAccessTokenTokenPostResponse =
  LoginForAccessTokenTokenPostResponses[keyof LoginForAccessTokenTokenPostResponses];

export type GetTournamentsTournamentsGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Filter
     */
    filter_?: 'ALL' | 'OPEN' | 'ARCHIVED';
    /**
     * Endpoint Name
     */
    endpoint_name?: string | null;
  };
  url: '/tournaments';
};

export type GetTournamentsTournamentsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetTournamentsTournamentsGetError =
  GetTournamentsTournamentsGetErrors[keyof GetTournamentsTournamentsGetErrors];

export type GetTournamentsTournamentsGetResponses = {
  /**
   * Successful Response
   */
  200: TournamentsResponse;
};

export type GetTournamentsTournamentsGetResponse =
  GetTournamentsTournamentsGetResponses[keyof GetTournamentsTournamentsGetResponses];

export type CreateTournamentTournamentsPostData = {
  body: TournamentBody;
  path?: never;
  query?: never;
  url: '/tournaments';
};

export type CreateTournamentTournamentsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateTournamentTournamentsPostError =
  CreateTournamentTournamentsPostErrors[keyof CreateTournamentTournamentsPostErrors];

export type CreateTournamentTournamentsPostResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type CreateTournamentTournamentsPostResponse =
  CreateTournamentTournamentsPostResponses[keyof CreateTournamentTournamentsPostResponses];

export type DeleteTournamentTournamentsTournamentIdDeleteData = {
  body?: never;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
  };
  query?: never;
  url: '/tournaments/{tournament_id}';
};

export type DeleteTournamentTournamentsTournamentIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteTournamentTournamentsTournamentIdDeleteError =
  DeleteTournamentTournamentsTournamentIdDeleteErrors[keyof DeleteTournamentTournamentsTournamentIdDeleteErrors];

export type DeleteTournamentTournamentsTournamentIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type DeleteTournamentTournamentsTournamentIdDeleteResponse =
  DeleteTournamentTournamentsTournamentIdDeleteResponses[keyof DeleteTournamentTournamentsTournamentIdDeleteResponses];

export type GetTournamentTournamentsTournamentIdGetData = {
  body?: never;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
  };
  query?: never;
  url: '/tournaments/{tournament_id}';
};

export type GetTournamentTournamentsTournamentIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetTournamentTournamentsTournamentIdGetError =
  GetTournamentTournamentsTournamentIdGetErrors[keyof GetTournamentTournamentsTournamentIdGetErrors];

export type GetTournamentTournamentsTournamentIdGetResponses = {
  /**
   * Successful Response
   */
  200: TournamentResponse;
};

export type GetTournamentTournamentsTournamentIdGetResponse =
  GetTournamentTournamentsTournamentIdGetResponses[keyof GetTournamentTournamentsTournamentIdGetResponses];

export type UpdateTournamentByIdTournamentsTournamentIdPutData = {
  body: TournamentUpdateBody;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
  };
  query?: never;
  url: '/tournaments/{tournament_id}';
};

export type UpdateTournamentByIdTournamentsTournamentIdPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateTournamentByIdTournamentsTournamentIdPutError =
  UpdateTournamentByIdTournamentsTournamentIdPutErrors[keyof UpdateTournamentByIdTournamentsTournamentIdPutErrors];

export type UpdateTournamentByIdTournamentsTournamentIdPutResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type UpdateTournamentByIdTournamentsTournamentIdPutResponse =
  UpdateTournamentByIdTournamentsTournamentIdPutResponses[keyof UpdateTournamentByIdTournamentsTournamentIdPutResponses];

export type GetAvailableInputsTournamentsTournamentIdAvailableInputsGetData = {
  body?: never;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
  };
  query?: never;
  url: '/tournaments/{tournament_id}/available_inputs';
};

export type GetAvailableInputsTournamentsTournamentIdAvailableInputsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetAvailableInputsTournamentsTournamentIdAvailableInputsGetError =
  GetAvailableInputsTournamentsTournamentIdAvailableInputsGetErrors[keyof GetAvailableInputsTournamentsTournamentIdAvailableInputsGetErrors];

export type GetAvailableInputsTournamentsTournamentIdAvailableInputsGetResponses = {
  /**
   * Successful Response
   */
  200: StageItemInputOptionsResponse;
};

export type GetAvailableInputsTournamentsTournamentIdAvailableInputsGetResponse =
  GetAvailableInputsTournamentsTournamentIdAvailableInputsGetResponses[keyof GetAvailableInputsTournamentsTournamentIdAvailableInputsGetResponses];

export type GetBreaksTournamentsTournamentIdBreaksGetData = {
  body?: never;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
  };
  query?: never;
  url: '/tournaments/{tournament_id}/breaks';
};

export type GetBreaksTournamentsTournamentIdBreaksGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetBreaksTournamentsTournamentIdBreaksGetError =
  GetBreaksTournamentsTournamentIdBreaksGetErrors[keyof GetBreaksTournamentsTournamentIdBreaksGetErrors];

export type GetBreaksTournamentsTournamentIdBreaksGetResponses = {
  /**
   * Successful Response
   */
  200: TournamentBreaksResponse;
};

export type GetBreaksTournamentsTournamentIdBreaksGetResponse =
  GetBreaksTournamentsTournamentIdBreaksGetResponses[keyof GetBreaksTournamentsTournamentIdBreaksGetResponses];

export type CreateBreakTournamentsTournamentIdBreaksPostData = {
  body: TournamentBreakBody;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
  };
  query?: never;
  url: '/tournaments/{tournament_id}/breaks';
};

export type CreateBreakTournamentsTournamentIdBreaksPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateBreakTournamentsTournamentIdBreaksPostError =
  CreateBreakTournamentsTournamentIdBreaksPostErrors[keyof CreateBreakTournamentsTournamentIdBreaksPostErrors];

export type CreateBreakTournamentsTournamentIdBreaksPostResponses = {
  /**
   * Successful Response
   */
  200: SingleTournamentBreakResponse;
};

export type CreateBreakTournamentsTournamentIdBreaksPostResponse =
  CreateBreakTournamentsTournamentIdBreaksPostResponses[keyof CreateBreakTournamentsTournamentIdBreaksPostResponses];

export type DeleteBreakTournamentsTournamentIdBreaksBreakIdDeleteData = {
  body?: never;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
    /**
     * Break Id
     */
    break_id: number;
  };
  query?: never;
  url: '/tournaments/{tournament_id}/breaks/{break_id}';
};

export type DeleteBreakTournamentsTournamentIdBreaksBreakIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteBreakTournamentsTournamentIdBreaksBreakIdDeleteError =
  DeleteBreakTournamentsTournamentIdBreaksBreakIdDeleteErrors[keyof DeleteBreakTournamentsTournamentIdBreaksBreakIdDeleteErrors];

export type DeleteBreakTournamentsTournamentIdBreaksBreakIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type DeleteBreakTournamentsTournamentIdBreaksBreakIdDeleteResponse =
  DeleteBreakTournamentsTournamentIdBreaksBreakIdDeleteResponses[keyof DeleteBreakTournamentsTournamentIdBreaksBreakIdDeleteResponses];

export type UpdateBreakByIdTournamentsTournamentIdBreaksBreakIdPutData = {
  body: TournamentBreakBody;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
    /**
     * Break Id
     */
    break_id: number;
  };
  query?: never;
  url: '/tournaments/{tournament_id}/breaks/{break_id}';
};

export type UpdateBreakByIdTournamentsTournamentIdBreaksBreakIdPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateBreakByIdTournamentsTournamentIdBreaksBreakIdPutError =
  UpdateBreakByIdTournamentsTournamentIdBreaksBreakIdPutErrors[keyof UpdateBreakByIdTournamentsTournamentIdBreaksBreakIdPutErrors];

export type UpdateBreakByIdTournamentsTournamentIdBreaksBreakIdPutResponses = {
  /**
   * Successful Response
   */
  200: SingleTournamentBreakResponse;
};

export type UpdateBreakByIdTournamentsTournamentIdBreaksBreakIdPutResponse =
  UpdateBreakByIdTournamentsTournamentIdBreaksBreakIdPutResponses[keyof UpdateBreakByIdTournamentsTournamentIdBreaksBreakIdPutResponses];

export type ChangeStatusTournamentsTournamentIdChangeStatusPostData = {
  body: TournamentChangeStatusBody;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
  };
  query?: never;
  url: '/tournaments/{tournament_id}/change-status';
};

export type ChangeStatusTournamentsTournamentIdChangeStatusPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ChangeStatusTournamentsTournamentIdChangeStatusPostError =
  ChangeStatusTournamentsTournamentIdChangeStatusPostErrors[keyof ChangeStatusTournamentsTournamentIdChangeStatusPostErrors];

export type ChangeStatusTournamentsTournamentIdChangeStatusPostResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type ChangeStatusTournamentsTournamentIdChangeStatusPostResponse =
  ChangeStatusTournamentsTournamentIdChangeStatusPostResponses[keyof ChangeStatusTournamentsTournamentIdChangeStatusPostResponses];

export type ClearScheduleTournamentsTournamentIdClearSchedulePostData = {
  body?: never;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
  };
  query?: never;
  url: '/tournaments/{tournament_id}/clear_schedule';
};

export type ClearScheduleTournamentsTournamentIdClearSchedulePostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ClearScheduleTournamentsTournamentIdClearSchedulePostError =
  ClearScheduleTournamentsTournamentIdClearSchedulePostErrors[keyof ClearScheduleTournamentsTournamentIdClearSchedulePostErrors];

export type ClearScheduleTournamentsTournamentIdClearSchedulePostResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type ClearScheduleTournamentsTournamentIdClearSchedulePostResponse =
  ClearScheduleTournamentsTournamentIdClearSchedulePostResponses[keyof ClearScheduleTournamentsTournamentIdClearSchedulePostResponses];

export type GetCourtsTournamentsTournamentIdCourtsGetData = {
  body?: never;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
  };
  query?: never;
  url: '/tournaments/{tournament_id}/courts';
};

export type GetCourtsTournamentsTournamentIdCourtsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetCourtsTournamentsTournamentIdCourtsGetError =
  GetCourtsTournamentsTournamentIdCourtsGetErrors[keyof GetCourtsTournamentsTournamentIdCourtsGetErrors];

export type GetCourtsTournamentsTournamentIdCourtsGetResponses = {
  /**
   * Successful Response
   */
  200: CourtsResponse;
};

export type GetCourtsTournamentsTournamentIdCourtsGetResponse =
  GetCourtsTournamentsTournamentIdCourtsGetResponses[keyof GetCourtsTournamentsTournamentIdCourtsGetResponses];

export type CreateCourtTournamentsTournamentIdCourtsPostData = {
  body: CourtBody;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
  };
  query?: never;
  url: '/tournaments/{tournament_id}/courts';
};

export type CreateCourtTournamentsTournamentIdCourtsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateCourtTournamentsTournamentIdCourtsPostError =
  CreateCourtTournamentsTournamentIdCourtsPostErrors[keyof CreateCourtTournamentsTournamentIdCourtsPostErrors];

export type CreateCourtTournamentsTournamentIdCourtsPostResponses = {
  /**
   * Successful Response
   */
  200: SingleCourtResponse;
};

export type CreateCourtTournamentsTournamentIdCourtsPostResponse =
  CreateCourtTournamentsTournamentIdCourtsPostResponses[keyof CreateCourtTournamentsTournamentIdCourtsPostResponses];

export type DeleteCourtTournamentsTournamentIdCourtsCourtIdDeleteData = {
  body?: never;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
    /**
     * Court Id
     */
    court_id: number;
  };
  query?: never;
  url: '/tournaments/{tournament_id}/courts/{court_id}';
};

export type DeleteCourtTournamentsTournamentIdCourtsCourtIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteCourtTournamentsTournamentIdCourtsCourtIdDeleteError =
  DeleteCourtTournamentsTournamentIdCourtsCourtIdDeleteErrors[keyof DeleteCourtTournamentsTournamentIdCourtsCourtIdDeleteErrors];

export type DeleteCourtTournamentsTournamentIdCourtsCourtIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type DeleteCourtTournamentsTournamentIdCourtsCourtIdDeleteResponse =
  DeleteCourtTournamentsTournamentIdCourtsCourtIdDeleteResponses[keyof DeleteCourtTournamentsTournamentIdCourtsCourtIdDeleteResponses];

export type UpdateCourtByIdTournamentsTournamentIdCourtsCourtIdPutData = {
  body: CourtBody;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
    /**
     * Court Id
     */
    court_id: number;
  };
  query?: never;
  url: '/tournaments/{tournament_id}/courts/{court_id}';
};

export type UpdateCourtByIdTournamentsTournamentIdCourtsCourtIdPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateCourtByIdTournamentsTournamentIdCourtsCourtIdPutError =
  UpdateCourtByIdTournamentsTournamentIdCourtsCourtIdPutErrors[keyof UpdateCourtByIdTournamentsTournamentIdCourtsCourtIdPutErrors];

export type UpdateCourtByIdTournamentsTournamentIdCourtsCourtIdPutResponses = {
  /**
   * Successful Response
   */
  200: SingleCourtResponse;
};

export type UpdateCourtByIdTournamentsTournamentIdCourtsCourtIdPutResponse =
  UpdateCourtByIdTournamentsTournamentIdCourtsCourtIdPutResponses[keyof UpdateCourtByIdTournamentsTournamentIdCourtsCourtIdPutResponses];

export type GetTournamentLogoTournamentsTournamentIdLogoGetData = {
  body?: never;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
  };
  query?: never;
  url: '/tournaments/{tournament_id}/logo';
};

export type GetTournamentLogoTournamentsTournamentIdLogoGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetTournamentLogoTournamentsTournamentIdLogoGetError =
  GetTournamentLogoTournamentsTournamentIdLogoGetErrors[keyof GetTournamentLogoTournamentsTournamentIdLogoGetErrors];

export type GetTournamentLogoTournamentsTournamentIdLogoGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type UploadLogoTournamentsTournamentIdLogoPostData = {
  body?: BodyUploadLogoTournamentsTournamentIdLogoPost;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
  };
  query?: never;
  url: '/tournaments/{tournament_id}/logo';
};

export type UploadLogoTournamentsTournamentIdLogoPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UploadLogoTournamentsTournamentIdLogoPostError =
  UploadLogoTournamentsTournamentIdLogoPostErrors[keyof UploadLogoTournamentsTournamentIdLogoPostErrors];

export type UploadLogoTournamentsTournamentIdLogoPostResponses = {
  /**
   * Successful Response
   */
  200: TournamentResponse;
};

export type UploadLogoTournamentsTournamentIdLogoPostResponse =
  UploadLogoTournamentsTournamentIdLogoPostResponses[keyof UploadLogoTournamentsTournamentIdLogoPostResponses];

export type CreateMatchTournamentsTournamentIdMatchesPostData = {
  body: MatchCreateBodyFrontend;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
  };
  query?: never;
  url: '/tournaments/{tournament_id}/matches';
};

export type CreateMatchTournamentsTournamentIdMatchesPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateMatchTournamentsTournamentIdMatchesPostError =
  CreateMatchTournamentsTournamentIdMatchesPostErrors[keyof CreateMatchTournamentsTournamentIdMatchesPostErrors];

export type CreateMatchTournamentsTournamentIdMatchesPostResponses = {
  /**
   * Successful Response
   */
  200: SingleMatchResponse;
};

export type CreateMatchTournamentsTournamentIdMatchesPostResponse =
  CreateMatchTournamentsTournamentIdMatchesPostResponses[keyof CreateMatchTournamentsTournamentIdMatchesPostResponses];

export type DeleteMatchTournamentsTournamentIdMatchesMatchIdDeleteData = {
  body?: never;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
    /**
     * Match Id
     */
    match_id: number;
  };
  query?: never;
  url: '/tournaments/{tournament_id}/matches/{match_id}';
};

export type DeleteMatchTournamentsTournamentIdMatchesMatchIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteMatchTournamentsTournamentIdMatchesMatchIdDeleteError =
  DeleteMatchTournamentsTournamentIdMatchesMatchIdDeleteErrors[keyof DeleteMatchTournamentsTournamentIdMatchesMatchIdDeleteErrors];

export type DeleteMatchTournamentsTournamentIdMatchesMatchIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type DeleteMatchTournamentsTournamentIdMatchesMatchIdDeleteResponse =
  DeleteMatchTournamentsTournamentIdMatchesMatchIdDeleteResponses[keyof DeleteMatchTournamentsTournamentIdMatchesMatchIdDeleteResponses];

export type UpdateMatchByIdTournamentsTournamentIdMatchesMatchIdPutData = {
  body: MatchBody;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
    /**
     * Match Id
     */
    match_id: number;
  };
  query?: never;
  url: '/tournaments/{tournament_id}/matches/{match_id}';
};

export type UpdateMatchByIdTournamentsTournamentIdMatchesMatchIdPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateMatchByIdTournamentsTournamentIdMatchesMatchIdPutError =
  UpdateMatchByIdTournamentsTournamentIdMatchesMatchIdPutErrors[keyof UpdateMatchByIdTournamentsTournamentIdMatchesMatchIdPutErrors];

export type UpdateMatchByIdTournamentsTournamentIdMatchesMatchIdPutResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type UpdateMatchByIdTournamentsTournamentIdMatchesMatchIdPutResponse =
  UpdateMatchByIdTournamentsTournamentIdMatchesMatchIdPutResponses[keyof UpdateMatchByIdTournamentsTournamentIdMatchesMatchIdPutResponses];

export type RescheduleMatchTournamentsTournamentIdMatchesMatchIdReschedulePostData = {
  body: MatchRescheduleBody;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
    /**
     * Match Id
     */
    match_id: number;
  };
  query?: never;
  url: '/tournaments/{tournament_id}/matches/{match_id}/reschedule';
};

export type RescheduleMatchTournamentsTournamentIdMatchesMatchIdReschedulePostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RescheduleMatchTournamentsTournamentIdMatchesMatchIdReschedulePostError =
  RescheduleMatchTournamentsTournamentIdMatchesMatchIdReschedulePostErrors[keyof RescheduleMatchTournamentsTournamentIdMatchesMatchIdReschedulePostErrors];

export type RescheduleMatchTournamentsTournamentIdMatchesMatchIdReschedulePostResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type RescheduleMatchTournamentsTournamentIdMatchesMatchIdReschedulePostResponse =
  RescheduleMatchTournamentsTournamentIdMatchesMatchIdReschedulePostResponses[keyof RescheduleMatchTournamentsTournamentIdMatchesMatchIdReschedulePostResponses];

export type GetNextStageRankingsTournamentsTournamentIdNextStageRankingsGetData = {
  body?: never;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
  };
  query?: never;
  url: '/tournaments/{tournament_id}/next_stage_rankings';
};

export type GetNextStageRankingsTournamentsTournamentIdNextStageRankingsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetNextStageRankingsTournamentsTournamentIdNextStageRankingsGetError =
  GetNextStageRankingsTournamentsTournamentIdNextStageRankingsGetErrors[keyof GetNextStageRankingsTournamentsTournamentIdNextStageRankingsGetErrors];

export type GetNextStageRankingsTournamentsTournamentIdNextStageRankingsGetResponses = {
  /**
   * Successful Response
   */
  200: StageRankingResponse;
};

export type GetNextStageRankingsTournamentsTournamentIdNextStageRankingsGetResponse =
  GetNextStageRankingsTournamentsTournamentIdNextStageRankingsGetResponses[keyof GetNextStageRankingsTournamentsTournamentIdNextStageRankingsGetResponses];

export type GetOfficialsTournamentsTournamentIdOfficialsGetData = {
  body?: never;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
  };
  query?: never;
  url: '/tournaments/{tournament_id}/officials';
};

export type GetOfficialsTournamentsTournamentIdOfficialsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetOfficialsTournamentsTournamentIdOfficialsGetError =
  GetOfficialsTournamentsTournamentIdOfficialsGetErrors[keyof GetOfficialsTournamentsTournamentIdOfficialsGetErrors];

export type GetOfficialsTournamentsTournamentIdOfficialsGetResponses = {
  /**
   * Successful Response
   */
  200: OfficialsResponse;
};

export type GetOfficialsTournamentsTournamentIdOfficialsGetResponse =
  GetOfficialsTournamentsTournamentIdOfficialsGetResponses[keyof GetOfficialsTournamentsTournamentIdOfficialsGetResponses];

export type CreateOfficialTournamentsTournamentIdOfficialsPostData = {
  body: OfficialBody;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
  };
  query?: never;
  url: '/tournaments/{tournament_id}/officials';
};

export type CreateOfficialTournamentsTournamentIdOfficialsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateOfficialTournamentsTournamentIdOfficialsPostError =
  CreateOfficialTournamentsTournamentIdOfficialsPostErrors[keyof CreateOfficialTournamentsTournamentIdOfficialsPostErrors];

export type CreateOfficialTournamentsTournamentIdOfficialsPostResponses = {
  /**
   * Successful Response
   */
  200: SingleOfficialResponse;
};

export type CreateOfficialTournamentsTournamentIdOfficialsPostResponse =
  CreateOfficialTournamentsTournamentIdOfficialsPostResponses[keyof CreateOfficialTournamentsTournamentIdOfficialsPostResponses];

export type AutoAssignOfficialsTournamentsTournamentIdOfficialsAutoAssignPostData = {
  body?: never;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
  };
  query?: never;
  url: '/tournaments/{tournament_id}/officials/auto_assign';
};

export type AutoAssignOfficialsTournamentsTournamentIdOfficialsAutoAssignPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AutoAssignOfficialsTournamentsTournamentIdOfficialsAutoAssignPostError =
  AutoAssignOfficialsTournamentsTournamentIdOfficialsAutoAssignPostErrors[keyof AutoAssignOfficialsTournamentsTournamentIdOfficialsAutoAssignPostErrors];

export type AutoAssignOfficialsTournamentsTournamentIdOfficialsAutoAssignPostResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type AutoAssignOfficialsTournamentsTournamentIdOfficialsAutoAssignPostResponse =
  AutoAssignOfficialsTournamentsTournamentIdOfficialsAutoAssignPostResponses[keyof AutoAssignOfficialsTournamentsTournamentIdOfficialsAutoAssignPostResponses];

export type ClearOfficialAssignmentsTournamentsTournamentIdOfficialsClearAssignmentsPostData = {
  body?: never;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
  };
  query?: never;
  url: '/tournaments/{tournament_id}/officials/clear_assignments';
};

export type ClearOfficialAssignmentsTournamentsTournamentIdOfficialsClearAssignmentsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ClearOfficialAssignmentsTournamentsTournamentIdOfficialsClearAssignmentsPostError =
  ClearOfficialAssignmentsTournamentsTournamentIdOfficialsClearAssignmentsPostErrors[keyof ClearOfficialAssignmentsTournamentsTournamentIdOfficialsClearAssignmentsPostErrors];

export type ClearOfficialAssignmentsTournamentsTournamentIdOfficialsClearAssignmentsPostResponses =
  {
    /**
     * Successful Response
     */
    200: SuccessResponse;
  };

export type ClearOfficialAssignmentsTournamentsTournamentIdOfficialsClearAssignmentsPostResponse =
  ClearOfficialAssignmentsTournamentsTournamentIdOfficialsClearAssignmentsPostResponses[keyof ClearOfficialAssignmentsTournamentsTournamentIdOfficialsClearAssignmentsPostResponses];

export type DeleteOfficialTournamentsTournamentIdOfficialsOfficialIdDeleteData = {
  body?: never;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
    /**
     * Official Id
     */
    official_id: number;
  };
  query?: never;
  url: '/tournaments/{tournament_id}/officials/{official_id}';
};

export type DeleteOfficialTournamentsTournamentIdOfficialsOfficialIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteOfficialTournamentsTournamentIdOfficialsOfficialIdDeleteError =
  DeleteOfficialTournamentsTournamentIdOfficialsOfficialIdDeleteErrors[keyof DeleteOfficialTournamentsTournamentIdOfficialsOfficialIdDeleteErrors];

export type DeleteOfficialTournamentsTournamentIdOfficialsOfficialIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type DeleteOfficialTournamentsTournamentIdOfficialsOfficialIdDeleteResponse =
  DeleteOfficialTournamentsTournamentIdOfficialsOfficialIdDeleteResponses[keyof DeleteOfficialTournamentsTournamentIdOfficialsOfficialIdDeleteResponses];

export type UpdateOfficialByIdTournamentsTournamentIdOfficialsOfficialIdPutData = {
  body: OfficialBody;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
    /**
     * Official Id
     */
    official_id: number;
  };
  query?: never;
  url: '/tournaments/{tournament_id}/officials/{official_id}';
};

export type UpdateOfficialByIdTournamentsTournamentIdOfficialsOfficialIdPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateOfficialByIdTournamentsTournamentIdOfficialsOfficialIdPutError =
  UpdateOfficialByIdTournamentsTournamentIdOfficialsOfficialIdPutErrors[keyof UpdateOfficialByIdTournamentsTournamentIdOfficialsOfficialIdPutErrors];

export type UpdateOfficialByIdTournamentsTournamentIdOfficialsOfficialIdPutResponses = {
  /**
   * Successful Response
   */
  200: SingleOfficialResponse;
};

export type UpdateOfficialByIdTournamentsTournamentIdOfficialsOfficialIdPutResponse =
  UpdateOfficialByIdTournamentsTournamentIdOfficialsOfficialIdPutResponses[keyof UpdateOfficialByIdTournamentsTournamentIdOfficialsOfficialIdPutResponses];

export type GetPlayersTournamentsTournamentIdPlayersGetData = {
  body?: never;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
  };
  query?: {
    /**
     * Not In Team
     */
    not_in_team?: boolean;
    /**
     * Limit
     *
     * Max number of results in a single page.
     */
    limit?: number;
    /**
     * Offset
     *
     * Filter results starting from this offset.
     */
    offset?: number;
    /**
     * Sort Direction
     */
    sort_direction?: 'asc' | 'desc';
    /**
     * Sort By
     */
    sort_by?:
      | 'name'
      | 'elo_score'
      | 'swiss_score'
      | 'wins'
      | 'draws'
      | 'losses'
      | 'active'
      | 'created';
  };
  url: '/tournaments/{tournament_id}/players';
};

export type GetPlayersTournamentsTournamentIdPlayersGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetPlayersTournamentsTournamentIdPlayersGetError =
  GetPlayersTournamentsTournamentIdPlayersGetErrors[keyof GetPlayersTournamentsTournamentIdPlayersGetErrors];

export type GetPlayersTournamentsTournamentIdPlayersGetResponses = {
  /**
   * Successful Response
   */
  200: PlayersResponse;
};

export type GetPlayersTournamentsTournamentIdPlayersGetResponse =
  GetPlayersTournamentsTournamentIdPlayersGetResponses[keyof GetPlayersTournamentsTournamentIdPlayersGetResponses];

export type CreateSinglePlayerTournamentsTournamentIdPlayersPostData = {
  body: PlayerBody;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
  };
  query?: never;
  url: '/tournaments/{tournament_id}/players';
};

export type CreateSinglePlayerTournamentsTournamentIdPlayersPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateSinglePlayerTournamentsTournamentIdPlayersPostError =
  CreateSinglePlayerTournamentsTournamentIdPlayersPostErrors[keyof CreateSinglePlayerTournamentsTournamentIdPlayersPostErrors];

export type CreateSinglePlayerTournamentsTournamentIdPlayersPostResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type CreateSinglePlayerTournamentsTournamentIdPlayersPostResponse =
  CreateSinglePlayerTournamentsTournamentIdPlayersPostResponses[keyof CreateSinglePlayerTournamentsTournamentIdPlayersPostResponses];

export type DeletePlayerTournamentsTournamentIdPlayersPlayerIdDeleteData = {
  body?: never;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
    /**
     * Player Id
     */
    player_id: number;
  };
  query?: never;
  url: '/tournaments/{tournament_id}/players/{player_id}';
};

export type DeletePlayerTournamentsTournamentIdPlayersPlayerIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeletePlayerTournamentsTournamentIdPlayersPlayerIdDeleteError =
  DeletePlayerTournamentsTournamentIdPlayersPlayerIdDeleteErrors[keyof DeletePlayerTournamentsTournamentIdPlayersPlayerIdDeleteErrors];

export type DeletePlayerTournamentsTournamentIdPlayersPlayerIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type DeletePlayerTournamentsTournamentIdPlayersPlayerIdDeleteResponse =
  DeletePlayerTournamentsTournamentIdPlayersPlayerIdDeleteResponses[keyof DeletePlayerTournamentsTournamentIdPlayersPlayerIdDeleteResponses];

export type UpdatePlayerByIdTournamentsTournamentIdPlayersPlayerIdPutData = {
  body: PlayerBody;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
    /**
     * Player Id
     */
    player_id: number;
  };
  query?: never;
  url: '/tournaments/{tournament_id}/players/{player_id}';
};

export type UpdatePlayerByIdTournamentsTournamentIdPlayersPlayerIdPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdatePlayerByIdTournamentsTournamentIdPlayersPlayerIdPutError =
  UpdatePlayerByIdTournamentsTournamentIdPlayersPlayerIdPutErrors[keyof UpdatePlayerByIdTournamentsTournamentIdPlayersPlayerIdPutErrors];

export type UpdatePlayerByIdTournamentsTournamentIdPlayersPlayerIdPutResponses = {
  /**
   * Successful Response
   */
  200: SinglePlayerResponse;
};

export type UpdatePlayerByIdTournamentsTournamentIdPlayersPlayerIdPutResponse =
  UpdatePlayerByIdTournamentsTournamentIdPlayersPlayerIdPutResponses[keyof UpdatePlayerByIdTournamentsTournamentIdPlayersPlayerIdPutResponses];

export type CreateMultiplePlayersTournamentsTournamentIdPlayersMultiPostData = {
  body: PlayerMultiBody;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
  };
  query?: never;
  url: '/tournaments/{tournament_id}/players_multi';
};

export type CreateMultiplePlayersTournamentsTournamentIdPlayersMultiPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateMultiplePlayersTournamentsTournamentIdPlayersMultiPostError =
  CreateMultiplePlayersTournamentsTournamentIdPlayersMultiPostErrors[keyof CreateMultiplePlayersTournamentsTournamentIdPlayersMultiPostErrors];

export type CreateMultiplePlayersTournamentsTournamentIdPlayersMultiPostResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type CreateMultiplePlayersTournamentsTournamentIdPlayersMultiPostResponse =
  CreateMultiplePlayersTournamentsTournamentIdPlayersMultiPostResponses[keyof CreateMultiplePlayersTournamentsTournamentIdPlayersMultiPostResponses];

export type GetRankingsTournamentsTournamentIdRankingsGetData = {
  body?: never;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
  };
  query?: never;
  url: '/tournaments/{tournament_id}/rankings';
};

export type GetRankingsTournamentsTournamentIdRankingsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetRankingsTournamentsTournamentIdRankingsGetError =
  GetRankingsTournamentsTournamentIdRankingsGetErrors[keyof GetRankingsTournamentsTournamentIdRankingsGetErrors];

export type GetRankingsTournamentsTournamentIdRankingsGetResponses = {
  /**
   * Successful Response
   */
  200: RankingsResponse;
};

export type GetRankingsTournamentsTournamentIdRankingsGetResponse =
  GetRankingsTournamentsTournamentIdRankingsGetResponses[keyof GetRankingsTournamentsTournamentIdRankingsGetResponses];

export type CreateRankingTournamentsTournamentIdRankingsPostData = {
  body: RankingCreateBody;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
  };
  query?: never;
  url: '/tournaments/{tournament_id}/rankings';
};

export type CreateRankingTournamentsTournamentIdRankingsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateRankingTournamentsTournamentIdRankingsPostError =
  CreateRankingTournamentsTournamentIdRankingsPostErrors[keyof CreateRankingTournamentsTournamentIdRankingsPostErrors];

export type CreateRankingTournamentsTournamentIdRankingsPostResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type CreateRankingTournamentsTournamentIdRankingsPostResponse =
  CreateRankingTournamentsTournamentIdRankingsPostResponses[keyof CreateRankingTournamentsTournamentIdRankingsPostResponses];

export type DeleteRankingTournamentsTournamentIdRankingsRankingIdDeleteData = {
  body?: never;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
    /**
     * Ranking Id
     */
    ranking_id: number;
  };
  query?: never;
  url: '/tournaments/{tournament_id}/rankings/{ranking_id}';
};

export type DeleteRankingTournamentsTournamentIdRankingsRankingIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteRankingTournamentsTournamentIdRankingsRankingIdDeleteError =
  DeleteRankingTournamentsTournamentIdRankingsRankingIdDeleteErrors[keyof DeleteRankingTournamentsTournamentIdRankingsRankingIdDeleteErrors];

export type DeleteRankingTournamentsTournamentIdRankingsRankingIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type DeleteRankingTournamentsTournamentIdRankingsRankingIdDeleteResponse =
  DeleteRankingTournamentsTournamentIdRankingsRankingIdDeleteResponses[keyof DeleteRankingTournamentsTournamentIdRankingsRankingIdDeleteResponses];

export type UpdateRankingByIdTournamentsTournamentIdRankingsRankingIdPutData = {
  body: RankingBody;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
    /**
     * Ranking Id
     */
    ranking_id: number;
  };
  query?: never;
  url: '/tournaments/{tournament_id}/rankings/{ranking_id}';
};

export type UpdateRankingByIdTournamentsTournamentIdRankingsRankingIdPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateRankingByIdTournamentsTournamentIdRankingsRankingIdPutError =
  UpdateRankingByIdTournamentsTournamentIdRankingsRankingIdPutErrors[keyof UpdateRankingByIdTournamentsTournamentIdRankingsRankingIdPutErrors];

export type UpdateRankingByIdTournamentsTournamentIdRankingsRankingIdPutResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type UpdateRankingByIdTournamentsTournamentIdRankingsRankingIdPutResponse =
  UpdateRankingByIdTournamentsTournamentIdRankingsRankingIdPutResponses[keyof UpdateRankingByIdTournamentsTournamentIdRankingsRankingIdPutResponses];

export type CreateRoundTournamentsTournamentIdRoundsPostData = {
  body: RoundCreateBody;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
  };
  query?: never;
  url: '/tournaments/{tournament_id}/rounds';
};

export type CreateRoundTournamentsTournamentIdRoundsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateRoundTournamentsTournamentIdRoundsPostError =
  CreateRoundTournamentsTournamentIdRoundsPostErrors[keyof CreateRoundTournamentsTournamentIdRoundsPostErrors];

export type CreateRoundTournamentsTournamentIdRoundsPostResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type CreateRoundTournamentsTournamentIdRoundsPostResponse =
  CreateRoundTournamentsTournamentIdRoundsPostResponses[keyof CreateRoundTournamentsTournamentIdRoundsPostResponses];

export type DeleteRoundTournamentsTournamentIdRoundsRoundIdDeleteData = {
  body?: never;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
    /**
     * Round Id
     */
    round_id: number;
  };
  query?: never;
  url: '/tournaments/{tournament_id}/rounds/{round_id}';
};

export type DeleteRoundTournamentsTournamentIdRoundsRoundIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteRoundTournamentsTournamentIdRoundsRoundIdDeleteError =
  DeleteRoundTournamentsTournamentIdRoundsRoundIdDeleteErrors[keyof DeleteRoundTournamentsTournamentIdRoundsRoundIdDeleteErrors];

export type DeleteRoundTournamentsTournamentIdRoundsRoundIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type DeleteRoundTournamentsTournamentIdRoundsRoundIdDeleteResponse =
  DeleteRoundTournamentsTournamentIdRoundsRoundIdDeleteResponses[keyof DeleteRoundTournamentsTournamentIdRoundsRoundIdDeleteResponses];

export type UpdateRoundByIdTournamentsTournamentIdRoundsRoundIdPutData = {
  body: RoundUpdateBody;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
    /**
     * Round Id
     */
    round_id: number;
  };
  query?: never;
  url: '/tournaments/{tournament_id}/rounds/{round_id}';
};

export type UpdateRoundByIdTournamentsTournamentIdRoundsRoundIdPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateRoundByIdTournamentsTournamentIdRoundsRoundIdPutError =
  UpdateRoundByIdTournamentsTournamentIdRoundsRoundIdPutErrors[keyof UpdateRoundByIdTournamentsTournamentIdRoundsRoundIdPutErrors];

export type UpdateRoundByIdTournamentsTournamentIdRoundsRoundIdPutResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type UpdateRoundByIdTournamentsTournamentIdRoundsRoundIdPutResponse =
  UpdateRoundByIdTournamentsTournamentIdRoundsRoundIdPutResponses[keyof UpdateRoundByIdTournamentsTournamentIdRoundsRoundIdPutResponses];

export type ScheduleMatchesTournamentsTournamentIdScheduleMatchesPostData = {
  body?: never;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
  };
  query?: never;
  url: '/tournaments/{tournament_id}/schedule_matches';
};

export type ScheduleMatchesTournamentsTournamentIdScheduleMatchesPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ScheduleMatchesTournamentsTournamentIdScheduleMatchesPostError =
  ScheduleMatchesTournamentsTournamentIdScheduleMatchesPostErrors[keyof ScheduleMatchesTournamentsTournamentIdScheduleMatchesPostErrors];

export type ScheduleMatchesTournamentsTournamentIdScheduleMatchesPostResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type ScheduleMatchesTournamentsTournamentIdScheduleMatchesPostResponse =
  ScheduleMatchesTournamentsTournamentIdScheduleMatchesPostResponses[keyof ScheduleMatchesTournamentsTournamentIdScheduleMatchesPostResponses];

export type CreateStageItemTournamentsTournamentIdStageItemsPostData = {
  body: StageItemCreateBody;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
  };
  query?: never;
  url: '/tournaments/{tournament_id}/stage_items';
};

export type CreateStageItemTournamentsTournamentIdStageItemsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateStageItemTournamentsTournamentIdStageItemsPostError =
  CreateStageItemTournamentsTournamentIdStageItemsPostErrors[keyof CreateStageItemTournamentsTournamentIdStageItemsPostErrors];

export type CreateStageItemTournamentsTournamentIdStageItemsPostResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type CreateStageItemTournamentsTournamentIdStageItemsPostResponse =
  CreateStageItemTournamentsTournamentIdStageItemsPostResponses[keyof CreateStageItemTournamentsTournamentIdStageItemsPostResponses];

export type DeleteStageItemTournamentsTournamentIdStageItemsStageItemIdDeleteData = {
  body?: never;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
    /**
     * Stage Item Id
     */
    stage_item_id: number;
  };
  query?: never;
  url: '/tournaments/{tournament_id}/stage_items/{stage_item_id}';
};

export type DeleteStageItemTournamentsTournamentIdStageItemsStageItemIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteStageItemTournamentsTournamentIdStageItemsStageItemIdDeleteError =
  DeleteStageItemTournamentsTournamentIdStageItemsStageItemIdDeleteErrors[keyof DeleteStageItemTournamentsTournamentIdStageItemsStageItemIdDeleteErrors];

export type DeleteStageItemTournamentsTournamentIdStageItemsStageItemIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type DeleteStageItemTournamentsTournamentIdStageItemsStageItemIdDeleteResponse =
  DeleteStageItemTournamentsTournamentIdStageItemsStageItemIdDeleteResponses[keyof DeleteStageItemTournamentsTournamentIdStageItemsStageItemIdDeleteResponses];

export type UpdateStageItemTournamentsTournamentIdStageItemsStageItemIdPutData = {
  body: StageItemUpdateBody;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
    /**
     * Stage Item Id
     */
    stage_item_id: number;
  };
  query?: never;
  url: '/tournaments/{tournament_id}/stage_items/{stage_item_id}';
};

export type UpdateStageItemTournamentsTournamentIdStageItemsStageItemIdPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateStageItemTournamentsTournamentIdStageItemsStageItemIdPutError =
  UpdateStageItemTournamentsTournamentIdStageItemsStageItemIdPutErrors[keyof UpdateStageItemTournamentsTournamentIdStageItemsStageItemIdPutErrors];

export type UpdateStageItemTournamentsTournamentIdStageItemsStageItemIdPutResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type UpdateStageItemTournamentsTournamentIdStageItemsStageItemIdPutResponse =
  UpdateStageItemTournamentsTournamentIdStageItemsStageItemIdPutResponses[keyof UpdateStageItemTournamentsTournamentIdStageItemsStageItemIdPutResponses];

export type UpdateStageItemInputTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutData =
  {
    /**
     * Stage Item Body
     */
    body:
      | StageItemInputUpdateBodyTentative
      | StageItemInputUpdateBodyFinal
      | StageItemInputUpdateBodyEmpty;
    path: {
      /**
       * Tournament Id
       */
      tournament_id: number;
      /**
       * Stage Item Id
       */
      stage_item_id: number;
      /**
       * Stage Item Input Id
       */
      stage_item_input_id: number;
    };
    query?: never;
    url: '/tournaments/{tournament_id}/stage_items/{stage_item_id}/inputs/{stage_item_input_id}';
  };

export type UpdateStageItemInputTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutErrors =
  {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };

export type UpdateStageItemInputTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutError =
  UpdateStageItemInputTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutErrors[keyof UpdateStageItemInputTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutErrors];

export type UpdateStageItemInputTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutResponses =
  {
    /**
     * Successful Response
     */
    200: SuccessResponse;
  };

export type UpdateStageItemInputTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutResponse =
  UpdateStageItemInputTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutResponses[keyof UpdateStageItemInputTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutResponses];

export type StartNextRoundTournamentsTournamentIdStageItemsStageItemIdStartNextRoundPostData = {
  body: StageItemActivateNextBody;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
    /**
     * Stage Item Id
     */
    stage_item_id: number;
  };
  query?: {
    /**
     * Elo Diff Threshold
     */
    elo_diff_threshold?: number;
    /**
     * Iterations
     */
    iterations?: number;
    /**
     * Only Recommended
     */
    only_recommended?: boolean;
  };
  url: '/tournaments/{tournament_id}/stage_items/{stage_item_id}/start_next_round';
};

export type StartNextRoundTournamentsTournamentIdStageItemsStageItemIdStartNextRoundPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type StartNextRoundTournamentsTournamentIdStageItemsStageItemIdStartNextRoundPostError =
  StartNextRoundTournamentsTournamentIdStageItemsStageItemIdStartNextRoundPostErrors[keyof StartNextRoundTournamentsTournamentIdStageItemsStageItemIdStartNextRoundPostErrors];

export type StartNextRoundTournamentsTournamentIdStageItemsStageItemIdStartNextRoundPostResponses =
  {
    /**
     * Successful Response
     */
    200: SuccessResponse;
  };

export type StartNextRoundTournamentsTournamentIdStageItemsStageItemIdStartNextRoundPostResponse =
  StartNextRoundTournamentsTournamentIdStageItemsStageItemIdStartNextRoundPostResponses[keyof StartNextRoundTournamentsTournamentIdStageItemsStageItemIdStartNextRoundPostResponses];

export type GetMatchesToScheduleTournamentsTournamentIdStageItemsStageItemIdUpcomingMatchesGetData =
  {
    body?: never;
    path: {
      /**
       * Tournament Id
       */
      tournament_id: number;
      /**
       * Stage Item Id
       */
      stage_item_id: number;
    };
    query?: {
      /**
       * Elo Diff Threshold
       */
      elo_diff_threshold?: number;
      /**
       * Iterations
       */
      iterations?: number;
      /**
       * Only Recommended
       */
      only_recommended?: boolean;
      /**
       * Limit
       */
      limit?: number;
    };
    url: '/tournaments/{tournament_id}/stage_items/{stage_item_id}/upcoming_matches';
  };

export type GetMatchesToScheduleTournamentsTournamentIdStageItemsStageItemIdUpcomingMatchesGetErrors =
  {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };

export type GetMatchesToScheduleTournamentsTournamentIdStageItemsStageItemIdUpcomingMatchesGetError =
  GetMatchesToScheduleTournamentsTournamentIdStageItemsStageItemIdUpcomingMatchesGetErrors[keyof GetMatchesToScheduleTournamentsTournamentIdStageItemsStageItemIdUpcomingMatchesGetErrors];

export type GetMatchesToScheduleTournamentsTournamentIdStageItemsStageItemIdUpcomingMatchesGetResponses =
  {
    /**
     * Successful Response
     */
    200: UpcomingMatchesResponse;
  };

export type GetMatchesToScheduleTournamentsTournamentIdStageItemsStageItemIdUpcomingMatchesGetResponse =
  GetMatchesToScheduleTournamentsTournamentIdStageItemsStageItemIdUpcomingMatchesGetResponses[keyof GetMatchesToScheduleTournamentsTournamentIdStageItemsStageItemIdUpcomingMatchesGetResponses];

export type GetStagesTournamentsTournamentIdStagesGetData = {
  body?: never;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
  };
  query?: {
    /**
     * No Draft Rounds
     */
    no_draft_rounds?: boolean;
  };
  url: '/tournaments/{tournament_id}/stages';
};

export type GetStagesTournamentsTournamentIdStagesGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetStagesTournamentsTournamentIdStagesGetError =
  GetStagesTournamentsTournamentIdStagesGetErrors[keyof GetStagesTournamentsTournamentIdStagesGetErrors];

export type GetStagesTournamentsTournamentIdStagesGetResponses = {
  /**
   * Successful Response
   */
  200: StagesWithStageItemsResponse;
};

export type GetStagesTournamentsTournamentIdStagesGetResponse =
  GetStagesTournamentsTournamentIdStagesGetResponses[keyof GetStagesTournamentsTournamentIdStagesGetResponses];

export type CreateStageTournamentsTournamentIdStagesPostData = {
  body?: never;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
  };
  query?: never;
  url: '/tournaments/{tournament_id}/stages';
};

export type CreateStageTournamentsTournamentIdStagesPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateStageTournamentsTournamentIdStagesPostError =
  CreateStageTournamentsTournamentIdStagesPostErrors[keyof CreateStageTournamentsTournamentIdStagesPostErrors];

export type CreateStageTournamentsTournamentIdStagesPostResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type CreateStageTournamentsTournamentIdStagesPostResponse =
  CreateStageTournamentsTournamentIdStagesPostResponses[keyof CreateStageTournamentsTournamentIdStagesPostResponses];

export type ActivateNextStageTournamentsTournamentIdStagesActivatePostData = {
  body: StageActivateBody;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
  };
  query?: never;
  url: '/tournaments/{tournament_id}/stages/activate';
};

export type ActivateNextStageTournamentsTournamentIdStagesActivatePostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ActivateNextStageTournamentsTournamentIdStagesActivatePostError =
  ActivateNextStageTournamentsTournamentIdStagesActivatePostErrors[keyof ActivateNextStageTournamentsTournamentIdStagesActivatePostErrors];

export type ActivateNextStageTournamentsTournamentIdStagesActivatePostResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type ActivateNextStageTournamentsTournamentIdStagesActivatePostResponse =
  ActivateNextStageTournamentsTournamentIdStagesActivatePostResponses[keyof ActivateNextStageTournamentsTournamentIdStagesActivatePostResponses];

export type DeleteStageTournamentsTournamentIdStagesStageIdDeleteData = {
  body?: never;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
    /**
     * Stage Id
     */
    stage_id: number;
  };
  query?: never;
  url: '/tournaments/{tournament_id}/stages/{stage_id}';
};

export type DeleteStageTournamentsTournamentIdStagesStageIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteStageTournamentsTournamentIdStagesStageIdDeleteError =
  DeleteStageTournamentsTournamentIdStagesStageIdDeleteErrors[keyof DeleteStageTournamentsTournamentIdStagesStageIdDeleteErrors];

export type DeleteStageTournamentsTournamentIdStagesStageIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type DeleteStageTournamentsTournamentIdStagesStageIdDeleteResponse =
  DeleteStageTournamentsTournamentIdStagesStageIdDeleteResponses[keyof DeleteStageTournamentsTournamentIdStagesStageIdDeleteResponses];

export type UpdateStageTournamentsTournamentIdStagesStageIdPutData = {
  body: StageUpdateBody;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
    /**
     * Stage Id
     */
    stage_id: number;
  };
  query?: never;
  url: '/tournaments/{tournament_id}/stages/{stage_id}';
};

export type UpdateStageTournamentsTournamentIdStagesStageIdPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateStageTournamentsTournamentIdStagesStageIdPutError =
  UpdateStageTournamentsTournamentIdStagesStageIdPutErrors[keyof UpdateStageTournamentsTournamentIdStagesStageIdPutErrors];

export type UpdateStageTournamentsTournamentIdStagesStageIdPutResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type UpdateStageTournamentsTournamentIdStagesStageIdPutResponse =
  UpdateStageTournamentsTournamentIdStagesStageIdPutResponses[keyof UpdateStageTournamentsTournamentIdStagesStageIdPutResponses];

export type GetTeamsTournamentsTournamentIdTeamsGetData = {
  body?: never;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
  };
  query?: {
    /**
     * Limit
     *
     * Max number of results in a single page.
     */
    limit?: number;
    /**
     * Offset
     *
     * Filter results starting from this offset.
     */
    offset?: number;
    /**
     * Sort Direction
     */
    sort_direction?: 'asc' | 'desc';
    /**
     * Sort By
     */
    sort_by?:
      | 'name'
      | 'elo_score'
      | 'swiss_score'
      | 'wins'
      | 'draws'
      | 'losses'
      | 'active'
      | 'created';
  };
  url: '/tournaments/{tournament_id}/teams';
};

export type GetTeamsTournamentsTournamentIdTeamsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetTeamsTournamentsTournamentIdTeamsGetError =
  GetTeamsTournamentsTournamentIdTeamsGetErrors[keyof GetTeamsTournamentsTournamentIdTeamsGetErrors];

export type GetTeamsTournamentsTournamentIdTeamsGetResponses = {
  /**
   * Successful Response
   */
  200: TeamsWithPlayersResponse;
};

export type GetTeamsTournamentsTournamentIdTeamsGetResponse =
  GetTeamsTournamentsTournamentIdTeamsGetResponses[keyof GetTeamsTournamentsTournamentIdTeamsGetResponses];

export type CreateTeamTournamentsTournamentIdTeamsPostData = {
  body: TeamBody;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
  };
  query?: never;
  url: '/tournaments/{tournament_id}/teams';
};

export type CreateTeamTournamentsTournamentIdTeamsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateTeamTournamentsTournamentIdTeamsPostError =
  CreateTeamTournamentsTournamentIdTeamsPostErrors[keyof CreateTeamTournamentsTournamentIdTeamsPostErrors];

export type CreateTeamTournamentsTournamentIdTeamsPostResponses = {
  /**
   * Successful Response
   */
  200: SingleTeamResponse;
};

export type CreateTeamTournamentsTournamentIdTeamsPostResponse =
  CreateTeamTournamentsTournamentIdTeamsPostResponses[keyof CreateTeamTournamentsTournamentIdTeamsPostResponses];

export type DeleteTeamTournamentsTournamentIdTeamsTeamIdDeleteData = {
  body?: never;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
    /**
     * Team Id
     */
    team_id: number;
  };
  query?: never;
  url: '/tournaments/{tournament_id}/teams/{team_id}';
};

export type DeleteTeamTournamentsTournamentIdTeamsTeamIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteTeamTournamentsTournamentIdTeamsTeamIdDeleteError =
  DeleteTeamTournamentsTournamentIdTeamsTeamIdDeleteErrors[keyof DeleteTeamTournamentsTournamentIdTeamsTeamIdDeleteErrors];

export type DeleteTeamTournamentsTournamentIdTeamsTeamIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type DeleteTeamTournamentsTournamentIdTeamsTeamIdDeleteResponse =
  DeleteTeamTournamentsTournamentIdTeamsTeamIdDeleteResponses[keyof DeleteTeamTournamentsTournamentIdTeamsTeamIdDeleteResponses];

export type UpdateTeamByIdTournamentsTournamentIdTeamsTeamIdPutData = {
  body: TeamBody;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
    /**
     * Team Id
     */
    team_id: number;
  };
  query?: never;
  url: '/tournaments/{tournament_id}/teams/{team_id}';
};

export type UpdateTeamByIdTournamentsTournamentIdTeamsTeamIdPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateTeamByIdTournamentsTournamentIdTeamsTeamIdPutError =
  UpdateTeamByIdTournamentsTournamentIdTeamsTeamIdPutErrors[keyof UpdateTeamByIdTournamentsTournamentIdTeamsTeamIdPutErrors];

export type UpdateTeamByIdTournamentsTournamentIdTeamsTeamIdPutResponses = {
  /**
   * Successful Response
   */
  200: SingleTeamResponse;
};

export type UpdateTeamByIdTournamentsTournamentIdTeamsTeamIdPutResponse =
  UpdateTeamByIdTournamentsTournamentIdTeamsTeamIdPutResponses[keyof UpdateTeamByIdTournamentsTournamentIdTeamsTeamIdPutResponses];

export type GetTeamLogoTournamentsTournamentIdTeamsTeamIdLogoGetData = {
  body?: never;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
    /**
     * Team Id
     */
    team_id: number;
  };
  query?: never;
  url: '/tournaments/{tournament_id}/teams/{team_id}/logo';
};

export type GetTeamLogoTournamentsTournamentIdTeamsTeamIdLogoGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetTeamLogoTournamentsTournamentIdTeamsTeamIdLogoGetError =
  GetTeamLogoTournamentsTournamentIdTeamsTeamIdLogoGetErrors[keyof GetTeamLogoTournamentsTournamentIdTeamsTeamIdLogoGetErrors];

export type GetTeamLogoTournamentsTournamentIdTeamsTeamIdLogoGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type UpdateTeamLogoTournamentsTournamentIdTeamsTeamIdLogoPostData = {
  body?: BodyUpdateTeamLogoTournamentsTournamentIdTeamsTeamIdLogoPost;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
    /**
     * Team Id
     */
    team_id: number;
  };
  query?: never;
  url: '/tournaments/{tournament_id}/teams/{team_id}/logo';
};

export type UpdateTeamLogoTournamentsTournamentIdTeamsTeamIdLogoPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateTeamLogoTournamentsTournamentIdTeamsTeamIdLogoPostError =
  UpdateTeamLogoTournamentsTournamentIdTeamsTeamIdLogoPostErrors[keyof UpdateTeamLogoTournamentsTournamentIdTeamsTeamIdLogoPostErrors];

export type UpdateTeamLogoTournamentsTournamentIdTeamsTeamIdLogoPostResponses = {
  /**
   * Successful Response
   */
  200: SingleTeamResponse;
};

export type UpdateTeamLogoTournamentsTournamentIdTeamsTeamIdLogoPostResponse =
  UpdateTeamLogoTournamentsTournamentIdTeamsTeamIdLogoPostResponses[keyof UpdateTeamLogoTournamentsTournamentIdTeamsTeamIdLogoPostResponses];

export type CreateMultipleTeamsTournamentsTournamentIdTeamsMultiPostData = {
  body: TeamMultiBody;
  path: {
    /**
     * Tournament Id
     */
    tournament_id: number;
  };
  query?: never;
  url: '/tournaments/{tournament_id}/teams_multi';
};

export type CreateMultipleTeamsTournamentsTournamentIdTeamsMultiPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateMultipleTeamsTournamentsTournamentIdTeamsMultiPostError =
  CreateMultipleTeamsTournamentsTournamentIdTeamsMultiPostErrors[keyof CreateMultipleTeamsTournamentsTournamentIdTeamsMultiPostErrors];

export type CreateMultipleTeamsTournamentsTournamentIdTeamsMultiPostResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type CreateMultipleTeamsTournamentsTournamentIdTeamsMultiPostResponse =
  CreateMultipleTeamsTournamentsTournamentIdTeamsMultiPostResponses[keyof CreateMultipleTeamsTournamentsTournamentIdTeamsMultiPostResponses];

export type GetUserUsersMeGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/users/me';
};

export type GetUserUsersMeGetResponses = {
  /**
   * Successful Response
   */
  200: UserPublicResponse;
};

export type GetUserUsersMeGetResponse =
  GetUserUsersMeGetResponses[keyof GetUserUsersMeGetResponses];

export type RegisterUserUsersRegisterPostData = {
  body: UserToRegister;
  path?: never;
  query?: never;
  url: '/users/register';
};

export type RegisterUserUsersRegisterPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RegisterUserUsersRegisterPostError =
  RegisterUserUsersRegisterPostErrors[keyof RegisterUserUsersRegisterPostErrors];

export type RegisterUserUsersRegisterPostResponses = {
  /**
   * Successful Response
   */
  200: TokenResponse;
};

export type RegisterUserUsersRegisterPostResponse =
  RegisterUserUsersRegisterPostResponses[keyof RegisterUserUsersRegisterPostResponses];

export type RegisterDemoUserUsersRegisterDemoPostData = {
  body: DemoUserToRegister;
  path?: never;
  query?: never;
  url: '/users/register_demo';
};

export type RegisterDemoUserUsersRegisterDemoPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RegisterDemoUserUsersRegisterDemoPostError =
  RegisterDemoUserUsersRegisterDemoPostErrors[keyof RegisterDemoUserUsersRegisterDemoPostErrors];

export type RegisterDemoUserUsersRegisterDemoPostResponses = {
  /**
   * Successful Response
   */
  200: TokenResponse;
};

export type RegisterDemoUserUsersRegisterDemoPostResponse =
  RegisterDemoUserUsersRegisterDemoPostResponses[keyof RegisterDemoUserUsersRegisterDemoPostResponses];

export type GetMeUsersUserIdGetData = {
  body?: never;
  path: {
    /**
     * User Id
     */
    user_id: number;
  };
  query?: never;
  url: '/users/{user_id}';
};

export type GetMeUsersUserIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetMeUsersUserIdGetError = GetMeUsersUserIdGetErrors[keyof GetMeUsersUserIdGetErrors];

export type GetMeUsersUserIdGetResponses = {
  /**
   * Successful Response
   */
  200: UserPublicResponse;
};

export type GetMeUsersUserIdGetResponse =
  GetMeUsersUserIdGetResponses[keyof GetMeUsersUserIdGetResponses];

export type UpdateUserDetailsUsersUserIdPutData = {
  body: UserToUpdate;
  path: {
    /**
     * User Id
     */
    user_id: number;
  };
  query?: never;
  url: '/users/{user_id}';
};

export type UpdateUserDetailsUsersUserIdPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateUserDetailsUsersUserIdPutError =
  UpdateUserDetailsUsersUserIdPutErrors[keyof UpdateUserDetailsUsersUserIdPutErrors];

export type UpdateUserDetailsUsersUserIdPutResponses = {
  /**
   * Successful Response
   */
  200: UserPublicResponse;
};

export type UpdateUserDetailsUsersUserIdPutResponse =
  UpdateUserDetailsUsersUserIdPutResponses[keyof UpdateUserDetailsUsersUserIdPutResponses];

export type PutUserPasswordUsersUserIdPasswordPutData = {
  body: UserPasswordToUpdate;
  path: {
    /**
     * User Id
     */
    user_id: number;
  };
  query?: never;
  url: '/users/{user_id}/password';
};

export type PutUserPasswordUsersUserIdPasswordPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type PutUserPasswordUsersUserIdPasswordPutError =
  PutUserPasswordUsersUserIdPasswordPutErrors[keyof PutUserPasswordUsersUserIdPasswordPutErrors];

export type PutUserPasswordUsersUserIdPasswordPutResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type PutUserPasswordUsersUserIdPasswordPutResponse =
  PutUserPasswordUsersUserIdPasswordPutResponses[keyof PutUserPasswordUsersUserIdPasswordPutResponses];
